apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-generator-{{ .Values.env }}
  labels:
    app: random-generator-{{ .Values.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: random-generator-{{ .Values.env }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: random-generator-{{ .Values.env }}
    spec:
      containers:
        - name: random-generator
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
