replicaCount: 2
deployment:
  image:
    repository: danielofir/random-generator
    tag: latest
    pullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false

env: stage