apiVersion: v1
kind: Service
metadata:
  name: manipulator-{{ .Values.env }}
spec:
  selector:
    app: manipulator-{{ .Values.env }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 5000
  type: {{ .Values.service.type }}